  architecture-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOCAL_LLM_URL=http://ollama:11434
    depends_on:
      - ollama
      - mcp-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5